fix deployenv

diff --git a/ah-deployenv b/ah-deployenv
--- a/ah-deployenv
+++ b/ah-deployenv
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
-command -v foo >/dev/null 2>&1 || { echo >&2 "requires GNU parallel"; exit 1; }
 
-function ask(){
-	echo
-	[[ "$2" ]] && echo "$2"
-	text="$1"
-	read -p "$text [Yn] " DOIT
-	[[ "${DOIT:0:1}" == 'n' || "${DOIT:0:1}" == 'N' ]] && echo 'abort...' && exit 1
+command -v parallel >/dev/null 2>&1 || {
+	echo >&2 "I require GNU parallel but it's not installed.  Aborting.";
+	echo;
+	echo "Install GNU Parallel and run it once with: parallel --bibtex";
+	echo "This will activate the license so $(basename $0) can use it."; exit 1;
 }
 
+read -p "deploy $(ah env)? [Yn] " -n 1 -r
 echo
-ask "deploy $(ah env)?"
-ah status | grep $(ah env) | cut -f6 | parallel ssh {} sudo ah-client deploy
+if [[ $REPLY =~ ^[Yy]$ ]]; then
+  ah status | grep $(ah env) | cut -f6 | parallel ssh {} sudo ah-client deploy
+fi
